[build]
  publish = "public"
  command = "make netlify"
  environment = { BASE_URL = "https://esphome.io", API_DOCS_URL = "https://api-docs.esphome.io", PYTHON_VERSION = "3.12", HUGO_VERSION = "0.147.8" }

[context.beta]
  environment = { BASE_URL = "https://beta.esphome.io", API_DOCS_URL = "https://api-docs-beta.esphome.io" }

[context.next]
  environment = { BASE_URL = "https://next.esphome.io", API_DOCS_URL = "https://api-docs-dev.esphome.io" }

[context.new]
  environment = { BASE_URL = "https://new.esphome.io", API_DOCS_URL = "https://api-docs-dev.esphome.io" }

[context.production]
  environment = { BASE_URL = "https://esphome.io", API_DOCS_URL = "https://api-docs.esphome.io", PRODUCTION = "YES" }


# Caching HTML - 1 week
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Images, CSS, JS - 1 year, immutable. CSS and JS are fingerprinted
[[headers]]
  for = "/*.{png,jpg,jpeg,gif,webp,svg,css,js}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

